version: "3.3"
services:
  facture:
    build: .
    command:  dotnet bin/Release/net5.0/backend.dll
    environment:
      - DATABASE_URL=postgres://postgres:postgres@db:5432/postgres
      - ASPNETCORE_URLS=http://*:80
      - SSL_REQUIRED=0
    ports:
      - "5000:80"
    depends_on:
      - db
  db:
    image: postgres
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres