// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using facture.Data;

namespace facture.Migrations
{
    [DbContext(typeof(FactureDbContext))]
    [Migration("20220424053119_Reinitializing")]
    partial class Reinitializing
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 63)
                .HasAnnotation("ProductVersion", "5.0.10")
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

            modelBuilder.Entity("facture.Models.Client", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("adresse")
                        .HasColumnType("text");

                    b.Property<string>("email")
                        .HasColumnType("text");

                    b.Property<string>("fax")
                        .HasColumnType("text");

                    b.Property<int>("idCommunEntreprise")
                        .HasColumnType("integer");

                    b.Property<int>("idFiscal")
                        .HasColumnType("integer");

                    b.Property<string>("nom")
                        .HasColumnType("text");

                    b.Property<string>("nomRespo")
                        .HasColumnType("text");

                    b.Property<int>("patente")
                        .HasColumnType("integer");

                    b.Property<string>("pays")
                        .HasColumnType("text");

                    b.Property<string>("portable")
                        .HasColumnType("text");

                    b.Property<string>("prenom")
                        .HasColumnType("text");

                    b.Property<string>("raisonSociale")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("registreCommerce")
                        .HasColumnType("integer");

                    b.Property<string>("tel")
                        .HasColumnType("text");

                    b.Property<string>("typeSociete")
                        .HasColumnType("text");

                    b.Property<string>("ville")
                        .HasColumnType("text");

                    b.HasKey("id");

                    b.ToTable("Clients");
                });

            modelBuilder.Entity("facture.Models.Facture", b =>
                {
                    b.Property<int>("factureNumber")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<int>("clientId")
                        .HasColumnType("integer");

                    b.Property<string>("designation")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double>("prix")
                        .HasColumnType("double precision");

                    b.Property<int>("quantite")
                        .HasColumnType("integer");

                    b.Property<string>("reference")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("tva")
                        .HasColumnType("integer");

                    b.HasKey("factureNumber");

                    b.ToTable("Factures");
                });
#pragma warning restore 612, 618
        }
    }
}
